import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import { useRouter } from 'next/router';
import { useState } from 'react';

import ImageGallery from './components/ImageGallery';
import SearchBar from './components/SearchBar';

import Modal from './components/Modal';
import ModalImage from './components/ModalImage';

export default function App() {
  const router = useRouter();
  const [shownImageInModalSrc, setShownImageInModalSrc] = useState<string>('');
  const [shownImageInModalAlt, setShownImageInModalAlt] = useState<string>('');

  const [searchValue, setSearchValue] = useState<string>('');

  const [showModal, setShowModal] = useState<boolean>(false);

  interface FormSubmitLayout {
    target: { value: string }[];
  }

  const onSubmitForm = (event: React.SyntheticEvent & FormSubmitLayout) => {
    event.preventDefault();
    // const { PER_PAGE } = constants;
    if (searchValue === event.target[1].value.trim()) {
      event.target[1].value = '';
      return;
    }
    // setIsLoading(true);
    setSearchValue(event.target[1].value.trim());
    event.target[1].value = '';
    // router.push({
    //   pathname: '/[searchValue]',
    //   query: { searchValue: searchValue },
    // });

    //   try {
    //     const response = await fetchImageGallery(
    //       event.target[1].value.trim()
    //     );
    //     setImageGalleryList([...response.hits]);
    //     setTotalPages(Math.ceil(Number(response.totalHits) / PER_PAGE));
    //     setNextPage(2);

    //     event.target[1].value = '';
    //   } catch (error) {
    //     console.log('App ~ error', error);
    //   } finally {
    //     setIsLoading(false);
    //   }
  };

  const toggleModal = () => {
    setShowModal(!showModal);
  };

  const openImageInModal = ({
    largeImageURL,
    tags,
  }: {
    largeImageURL: string;
    tags: string;
  }) => {
    setShownImageInModalSrc(largeImageURL);
    setShownImageInModalAlt(tags);

    toggleModal();
    return;
  };

  return (
    <>
      <Head>
        <title>Next App Image Finder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchBar onSubmitForm={onSubmitForm} />
      <main className={styles.App}>
        <ImageGallery
          searchValue={searchValue}
          openImageInModal={openImageInModal}
        />
        {showModal && (
          <Modal onClose={toggleModal}>
            <ModalImage src={shownImageInModalSrc} alt={shownImageInModalAlt} />
          </Modal>
        )}
      </main>
      <footer className={styles.Footer}>
        Created By Next.JS & TypeScript-
        <a
          className={styles.FooterLink}
          href="https://github.com/Aleks-corp"
          target="_blank"
        >
          Aleks_corp
        </a>
      </footer>
    </>

    // <>
    //   <Head>
    //     <title>Create Next App</title>
    //     <meta name="description" content="Generated by create next app" />
    //     <meta name="viewport" content="width=device-width, initial-scale=1" />
    //     <link rel="icon" href="/favicon.ico" />
    //   </Head>
    //   <main className={`${styles.main} ${inter.className}`}>
    //     <div className={styles.description}>
    //       <p>
    //         Get started by editing&nbsp;
    //         <code className={styles.code}>pages/index.tsx</code>
    //       </p>
    //       <div>
    //         <a
    //           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //           target="_blank"
    //           rel="noopener noreferrer"
    //         >
    //           By{' '}
    //           <Image
    //             src="/vercel.svg"
    //             alt="Vercel Logo"
    //             className={styles.vercelLogo}
    //             width={100}
    //             height={24}
    //             priority
    //           />
    //         </a>
    //       </div>
    //     </div>

    //     <div className={styles.center}>
    //       <Image
    //         className={styles.logo}
    //         src="/next.svg"
    //         alt="Next.js Logo"
    //         width={180}
    //         height={37}
    //         priority
    //       />
    //     </div>

    //     <div className={styles.grid}>
    //       <a
    //         href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2>
    //           Docs <span>-&gt;</span>
    //         </h2>
    //         <p>
    //           Find in-depth information about Next.js features and&nbsp;API.
    //         </p>
    //       </a>

    //       <a
    //         href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2>
    //           Learn <span>-&gt;</span>
    //         </h2>
    //         <p>
    //           Learn about Next.js in an interactive course with&nbsp;quizzes!
    //         </p>
    //       </a>

    //       <a
    //         href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2>
    //           Templates <span>-&gt;</span>
    //         </h2>
    //         <p>
    //           Discover and deploy boilerplate example Next.js&nbsp;projects.
    //         </p>
    //       </a>

    //       <a
    //         href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
    //         className={styles.card}
    //         target="_blank"
    //         rel="noopener noreferrer"
    //       >
    //         <h2>
    //           Deploy <span>-&gt;</span>
    //         </h2>
    //         <p>
    //           Instantly deploy your Next.js site to a shareable URL
    //           with&nbsp;Vercel.
    //         </p>
    //       </a>
    //     </div>
    //   </main>
    // </>
  );
}
